execute pathogen#infect()

set nocompatible              " be iMproved, required
filetype off                  " required

"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" Plugins
Plugin 'airblade/vim-gitgutter'
Plugin 'ap/vim-buftabline'
Plugin 'ap/vim-css-color'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'elzr/vim-json'
Plugin 'ervandew/supertab'
Plugin 'fatih/vim-go'
Plugin 'jiangmiao/auto-pairs'
Plugin 'Go-Syntax'
Plugin 'godlygeek/tabular'
Plugin 'mattn/gist-vim'
Plugin 'roman/golden-ratio'
Plugin 'scrooloose/nerdtree'
Plugin 'shougo/neocomplete.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-git'
Plugin 'wincent/command-t'

" Themes
Plugin 'Blevs/vim-dzo'
Plugin 'geoffharcourt/one-dark.vim'
Plugin 'gosukiwi/vim-atom-dark'
Plugin 'kamwitsta/mythos'
Plugin 'KeitaNakamura/neodark.vim'
Plugin 'kristijanhusak/vim-hybrid-material'
Plugin 'maxst/flatcolor'
Plugin 'mkarmona/materialbox'
Plugin 'romainl/apprentice'
Plugin 'tyrannicaltoucan/vim-quantum'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" PERSONAL ADDITIONS
syntax on
colorscheme atom-dark-256

set background=dark
set number
set smarttab
set tabstop=4
set shiftwidth=4
set smartindent

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:go_fmt_command = "goimports"
