;;; liminal-dark-theme.el --- Liminal dark variant  -*- lexical-binding: t -*-

(deftheme liminal-dark "Minimal warm dark theme; the dark half of liminal.")

(let ((bg       "#1f1f24")
	  (bg-sub   "#27272d")
	  (bg-hi    "#313138")
	  (fg       "#ffffff")
	  (fg-dim   "#a0a6b0")
	  (fg-faint "#606670")
	  (kw       "#4ec4e6")
	  (str      "#ff8a7a")
	  (fn       "#d9c668")
	  (ty       "#83c9bc")
	  (bi       "#cda1ff")
	  (co       "#ffa14f")
	  (cm       "#838991")
	  (err      "#ff8a7a")
	  (wrn      "#ffa14f")
	  (ok       "#83c9bc")
	  (reg      "#43454b")
	  (search   "#3d3220")
	  (lazy     "#2d2818"))
  (custom-theme-set-faces
   'liminal-dark
   ;; Core
   `(default                          ((t :background ,bg :foreground ,fg)))
   `(cursor                           ((t :background ,fg)))
   `(fringe                           ((t :background ,bg :foreground ,fg-faint)))
   `(vertical-border                  ((t :foreground ,bg-sub)))
   `(window-divider                   ((t :foreground ,bg-sub)))
   `(window-divider-first-pixel       ((t :foreground ,bg-sub)))
   `(window-divider-last-pixel        ((t :foreground ,bg-sub)))
   `(fill-column-indicator            ((t :foreground ,fg-faint)))
   `(shadow                           ((t :foreground ,fg-faint)))
   ;; Line numbers
   `(line-number                      ((t :background ,bg :foreground ,fg-faint)))
   `(line-number-current-line         ((t :background ,bg :foreground ,fg-dim :weight bold)))
   ;; Mode line
   `(mode-line                        ((t :background ,bg-hi :foreground ,fg-dim :box nil)))
   `(mode-line-inactive               ((t :background ,bg-sub :foreground ,fg-faint :box nil)))
   `(mode-line-buffer-id              ((t :foreground ,fg :weight bold)))
   `(header-line                      ((t :background ,bg-sub :foreground ,fg-dim :box nil)))
   ;; Minibuffer
   `(minibuffer-prompt                ((t :foreground ,kw :weight bold)))
   ;; Selection / highlight
   `(region                           ((t :background ,reg :extend t)))
   `(secondary-selection              ((t :background ,bg-hi :extend t)))
   `(highlight                        ((t :background ,bg-hi)))
   `(hl-line                          ((t :background ,bg-sub :extend t)))
   ;; Search
   `(isearch                          ((t :background ,search :foreground ,fg :weight bold)))
   `(isearch-fail                     ((t :background ,err :foreground ,bg)))
   `(lazy-highlight                   ((t :background ,lazy)))
   `(match                            ((t :background "#1d3030" :foreground ,fg)))
   ;; Links
   `(link                             ((t :foreground ,kw :underline t)))
   `(link-visited                     ((t :foreground ,bi :underline t)))
   ;; Status
   `(error                            ((t :foreground ,err)))
   `(warning                          ((t :foreground ,wrn)))
   `(success                          ((t :foreground ,ok)))
   ;; Parens
   `(show-paren-match                 ((t :background ,bg-hi :foreground ,fn :weight bold)))
   `(show-paren-mismatch              ((t :background ,err :foreground ,bg)))
   ;; Completions
   `(completions-common-part          ((t :foreground ,kw)))
   `(completions-first-difference     ((t :foreground ,fn :weight bold)))
   ;; Font lock
   `(font-lock-builtin-face           ((t :foreground ,bi)))
   `(font-lock-comment-face           ((t :foreground ,cm :slant italic)))
   `(font-lock-comment-delimiter-face ((t :foreground ,cm :slant italic)))
   `(font-lock-constant-face          ((t :foreground ,co)))
   `(font-lock-doc-face               ((t :foreground ,cm :slant italic)))
   `(font-lock-function-name-face     ((t :foreground ,fn)))
   `(font-lock-keyword-face           ((t :foreground ,kw)))
   `(font-lock-negation-char-face     ((t :foreground ,err)))
   `(font-lock-preprocessor-face      ((t :foreground ,bi)))
   `(font-lock-string-face            ((t :foreground ,str)))
   `(font-lock-type-face              ((t :foreground ,ty)))
   `(font-lock-variable-name-face     ((t :foreground ,fg)))
   `(font-lock-warning-face           ((t :foreground ,wrn :weight bold)))
   ;; Flymake
   `(flymake-error                    ((t :underline (:style wave :color ,err))))
   `(flymake-warning                  ((t :underline (:style wave :color ,wrn))))
   `(flymake-note                     ((t :underline (:style wave :color ,ok))))
   ;; Compilation
   `(compilation-error                ((t :foreground ,err)))
   `(compilation-warning              ((t :foreground ,wrn)))
   `(compilation-info                 ((t :foreground ,ok)))
   ;; TODO keywords — amber = action, coral = danger, cyan = info
   `(mutecipher-todo-keyword          ((t :background "#3d2e18" :foreground ,wrn :weight bold)))
   `(mutecipher-hack-keyword          ((t :background "#3a1f1c" :foreground ,err :weight bold)))
   `(mutecipher-note-keyword          ((t :background "#1e2e45" :foreground ,kw  :weight bold)))
   ;; Icon colors
   `(mutecipher-icon-red              ((t :foreground ,co)))
   `(mutecipher-icon-yellow           ((t :foreground "#d9c668")))
   `(mutecipher-icon-blue             ((t :foreground ,kw)))
   `(mutecipher-icon-cyan             ((t :foreground "#4ec4e6")))
   `(mutecipher-icon-green            ((t :foreground ,str)))
   `(mutecipher-icon-purple           ((t :foreground ,bi)))
   `(mutecipher-icon-orange           ((t :foreground ,ty)))
   `(mutecipher-icon-dim              ((t :foreground ,fg-faint)))
   ;; Markdown
   `(mutecipher-markdown-code-block  ((t :background ,bg-sub :extend t)))
   `(mutecipher-markdown-inline-code ((t :background ,bg-sub)))
   `(mutecipher-markdown-table       ((t :foreground ,fg-dim)))
   ;; Org
   `(mutecipher-org-table-rule ((t :foreground ,fg-dim)))
   `(org-ellipsis              ((t :foreground ,fg-faint :underline nil)))
   `(org-hide                  ((t :foreground ,bg)))
   `(org-document-title        ((t :height 1.4 :weight bold)))
   `(org-document-info         ((t :foreground ,fg-dim)))
   `(org-document-info-keyword ((t :foreground ,fg-faint)))
   `(org-level-1               ((t :height 1.25 :weight bold)))
   `(org-level-2               ((t :height 1.10 :weight bold)))
   `(org-level-3               ((t :height 1.05 :weight bold)))
   `(org-level-4               ((t :height 1.0  :weight bold)))
   `(org-level-5               ((t :height 1.0)))
   `(org-level-6               ((t :height 1.0)))
   `(org-level-7               ((t :height 1.0)))
   `(org-level-8               ((t :height 1.0)))
   `(org-headline-done         ((t :foreground ,fg-faint)))
   `(org-block                 ((t :background ,bg-sub :extend t)))
   `(org-block-begin-line      ((t :background ,bg-sub :foreground ,fg-faint :extend t)))
   `(org-block-end-line        ((t :background ,bg-sub :foreground ,fg-faint :extend t)))
   `(org-code                  ((t :foreground ,ty)))
   `(org-verbatim              ((t :foreground ,fg-dim)))
   `(org-quote                 ((t :slant italic)))
   `(org-meta-line             ((t :foreground ,fg-faint)))
   `(org-special-keyword       ((t :foreground ,fg-faint)))))

(provide-theme 'liminal-dark)
;;; liminal-dark-theme.el ends here
