#!/usr/bin/env bash
#
# Author: Cory Hutchison
#
# Wrapper that bootstraps the platform, symlinks config files to the home directory and does some general 
# configuration.

set -e

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]] ; then DIR="$PWD" ; fi
# shellcheck source=script/misc
. "script/misc"

__info "bootstrapping system..."

script/platform
script/symlinks
script/generic

footer
