#!/usr/bin/env bash
#
# Author: Cory Hutchison
#
# Bootstraps all the specific config.sh files for different components of my system.

set -e

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]] ; then DIR="$PWD" ; fi
# shellcheck source=script/misc
. "script/misc"

installers=$(find . -name "config.sh")

result=0
for script in $installers ; do
  if test "$result" == "0"; then
    if [ -f "$script" ]; then
      env PLATFORM="$platform" PATH="$PATH" bash -c "${script}";
      result=$?

      if test "$result" -ne "0" ; then
        __error_message "error occurred in $script: $result"
      fi
    fi
  else
    __warning_message "not run due to error in previous installation script: $script"
    exit $result
  fi
done
