#!/usr/bin/env bash
#
# Author: Cory Hutchison
#

set -e

if [ -t 1 ]; then
  RED=$(printf '\033[31m')
  GREEN=$(printf '\033[32m')
  YELLOW=$(printf '\033[33m')
  BLUE=$(printf '\033[34m')
  BOLD=$(printf '\033[1m')
  RESET=$(printf '\033[m')
else
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  BOLD=""
  RESET=""
fi

__info() {
  printf "∴ ${BOLD}%s${RESET}\n" "$1"
}

__success_message() {
  printf "  ${GREEN}✓${RESET} %s\n" "$1"
}

__warning_message() {
  printf "  ${YELLOW}▲${RESET} %s\n" "$1"
}

__error_message() {
  printf "  ${RED}✗${RESET} %s\n" "$1"
}

footer() {
  echo -e "     ${GREEN}   _     _   ___ _ _"
  echo -e "      _| |___| |_|  _|_| |___ ___"
  echo -e "     | . | . |  _|  _| | | -_|_ -|"
  echo -e "     |___|___|_| |_| |_|_|___|___|${RESET}"
  echo -e "                      ...installed"
}

platform="$(uname -s)"
