#!/usr/bin/env bash
#
# Author: Cory Hutchison
#
# Calls all the platform specific configuration scripts.

set -e

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]] ; then DIR="$PWD" ; fi
# shellcheck source=script/misc
. "script/misc"

find . -name "${platform}.sh" | while read -p -r installer ; do sh "${installer}" ; done
