#!/bin/bash
# This script decrypts an inputted file using the
# password passed into an output file 

if [ "$#" -ne 3 ]; then
  echo "Illegal number of parameters"
  echo "usage: decrypt2file <input> <output> <password>"
else
  in=$1
  out=$2
  pass=$3

  openssl des3 -d -pass pass:$pass -in $in -out $out
fi
