#!/bin/bash
# This script decrypts an inputted file using the
# password passed in.

if [ "$#" -ne 2 ]; then
  echo "Illegal number of parameters"
  echo "usage: decrypt <filename> <password>"
else
  file=$1
  pass=$2

  openssl des3 -d -pass pass:$pass -in $1 | less
fi
