#!/bin/bash
# This script encrypts an inputted file using the salted DES3 using the 
# password passed in.

# Check for correct inputs
if [ "$#" -ne 1 ]; then
  printf "[\e[1;31m!!\e[0m] Illegal number of parameters\n"
  echo "usage: encrypt <filename>"
else
  # Get encrypted filename
  echo -n "Output file: "
  read out

  # Read password
  echo -n "Password: "
  read -s password
  echo

  # Encrypt
  openssl des3 -salt -pass pass:$password -out $out -in $1
fi
