#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Illegal number of parameters"
  echo "usage: encrypt <filename> <password>"
else
  file=$1
  pass=$2

  openssl des3 -salt -pass pass:$pass -out $file.new -in $file
fi
