#!/bin/bash
# git-livelog
# displays a live git log of your current git directory
# you can hit the letter q to escape and return to prompt

# catch CTRL-C, CTRL-Z, etc.
# YOU HAVE NO POWER HERE
trap '' SIGINT
trap '' SIGQUIT
trap '' SIGTSTP

# variable to hold the key pressed
key=''

printf "\e[?25l" # set the terminal cursor to invisible
while true
do
    clear # clear the screen
    # print out the git log (all purrdy like)
    git --no-pager log $1 --graph --all \
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' \
    --abbrev-commit --date=relative | head -35
    sleep 1 # wait for a second

    read -t 1 -n 1 key # read for user input

    if [[ $key = q ]] # if user entered q
    then
      break # quit the loop
    fi
done
printf "\e[?25h" # set the terminal cursor to visible
echo # move to next line
exit 0 # exit clean
