#!/bin/bash

echo -n "Password: "
read -s pass

printf "[ \e[4;32mupdating\e[0m ]\n"
echo $pass | sudo -S apt-get -qq update
wait
printf "[ \e[4;32mupgrading\e[0m ]\n"
sudo apt-get upgrade
wait
printf "[ \e[4;32mupgrading distribution\e[0m ]\n"
sudo apt-get dist-upgrade
wait
printf "[ \e[4;32mautocleaning\e[0m ]\n"
sudo apt-get autoclean
wait
printf "[ \e[4;32mautoremoving\e[0m ]\n"
sudo apt-get autoremove
wait
